### ISSUE TITLE
Could you add new function - past weather？

### ISSUE THREAD

**Issue by SaltFish-X** [Asvel/ffxiv-weather-bell#3]
I am using your website to watch ULK weather。But just check new weather。

If Blizzard weather in 12 a.m and 13 a.m，I check weather in 12:30 a.m. I don't know last Blizzard just past 30 min.
So trigger KX is impossible and futile

Could you add new function that watch today weather Whether it's past or not ？

**Comment by Asvel** [comment]
OK, I will add it after finishing some refactoring.

**Comment by Asvel** [comment]
I add past 2 eorzea day weathers, could this fit your needs?
